# Generated by Django 2.1.7 on 2019-03-25 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='INN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PhTherGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eng_name', models.CharField(max_length=50)),
                ('rus_name', models.CharField(max_length=50)),
                ('first_registration_date', models.DateField()),
                ('launch_date', models.DateField()),
                ('inns', models.ManyToManyField(to='app.INN')),
                ('ph_ther_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.PhTherGroup')),
            ],
        ),
    ]
