# Generated by Django 2.1.7 on 2019-03-26 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190326_1401'),
    ]

    operations = [
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='person',
            name='designation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Designation'),
        ),
    ]
