# Generated by Django 2.1.7 on 2019-03-26 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190326_1718'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Designation',
            new_name='Department',
        ),
        migrations.AddField(
            model_name='person',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Department'),
        ),
        migrations.AlterField(
            model_name='person',
            name='designation',
            field=models.CharField(max_length=100),
        ),
    ]
