# Generated by Django 2.1.7 on 2019-03-27 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20190327_1129'),
    ]

    operations = [
        migrations.CreateModel(
            name='ADR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_id', models.IntegerField(blank=True, null=True)),
                ('local_number', models.CharField(blank=True, max_length=20, null=True)),
                ('cioms_number', models.CharField(blank=True, max_length=20, null=True)),
                ('received_by_company', models.DateField(blank=True, null=True)),
                ('sent_to_regional_office', models.DateField(blank=True, null=True)),
                ('cioms_received', models.DateField(blank=True, null=True)),
                ('submitted', models.DateField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('batch_number', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('serious', models.BooleanField(blank=True, null=True)),
                ('expected', models.BooleanField(blank=True, null=True)),
                ('therapy_start_date', models.DateField(blank=True, null=True)),
                ('therapy_stop_date', models.DateField(blank=True, null=True)),
                ('indication', models.CharField(blank=True, max_length=20, null=True)),
                ('daily_dose', models.CharField(blank=True, max_length=20, null=True)),
                ('adr_onset_date', models.DateField(blank=True, null=True)),
                ('adr_outcome_date', models.DateField(blank=True, null=True)),
                ('source_is_patient', models.BooleanField(blank=True, null=True)),
                ('source_is_hcp', models.BooleanField(blank=True, null=True)),
                ('initial_reporter', models.CharField(blank=True, max_length=200, null=True)),
                ('created', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DosageForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PSUR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_id', models.IntegerField(blank=True, null=True)),
                ('number', models.CharField(blank=True, max_length=20, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('submitted', models.DateField(blank=True, null=True)),
                ('recommendations_rus', models.TextField()),
                ('recommendations_eng', models.TextField()),
                ('path_to_folder', models.CharField(blank=True, max_length=300, null=True)),
                ('created', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='inn',
            name='ibd',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inn',
            name='old_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='old_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='eng_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='first_registration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='inns',
            field=models.ManyToManyField(blank=True, null=True, to='app.INN'),
        ),
        migrations.AlterField(
            model_name='product',
            name='launch_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='ph_ther_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.PhTherGroup'),
        ),
        migrations.AddField(
            model_name='adr',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Product'),
        ),
        migrations.AddField(
            model_name='adr',
            name='secondary_reporter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Person'),
        ),
        migrations.AddField(
            model_name='product',
            name='dosage_form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.DosageForm'),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('eng_name', 'dosage_form')},
        ),
    ]
