# Generated by Django 2.1.7 on 2019-03-27 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_product_prescription_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='strength',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='eng_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='rus_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
