# Generated by Django 2.1.7 on 2019-04-01 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20190401_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
