# Generated by Django 2.1.7 on 2019-04-01 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_exam_sent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='created',
        ),
        migrations.RemoveField(
            model_name='person',
            name='created',
        ),
        migrations.RemoveField(
            model_name='psur',
            name='created',
        ),
        migrations.AlterField(
            model_name='adr',
            name='created',
            field=models.DateTimeField(),
        ),
    ]
