# Generated by Django 2.1.7 on 2019-04-01 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20190401_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_group',
            field=models.CharField(blank=True, choices=[('pv', 'pv'), ('med', 'med')], max_length=3, null=True),
        ),
    ]
